server {
    listen 80;
    listen [::]:80;
    server_name gitea.ikerdemo.cat;
    include /etc/nginx/snippets/acme-redirect.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name gitea.ikerdemo.cat;
    client_max_body_size 512M;

    ssl_certificate     /etc/letsencrypt/live/gitea.ikerdemo.cat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gitea.ikerdemo.cat/privkey.pem;
    include /etc/nginx/snippets/tls.conf;

    location / {
        set $upstream http://gitea:3000;
        proxy_pass $upstream;
        include /etc/nginx/snippets/proxy.conf;
    }
}
